# Copyright © 2023, Oracle and/or its affiliates.
# All rights reserved. Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Deploy ChatDB - Autonomous Database Select AI demonstration"
stackDescription: "Creates an ADB with MovieStream data plus the ChatDB APEX demo app"
schemaVersion: 1.1.0
version: "20230112"
locale: "en"
groupings:
  - title: "General Settings"
    visible: true
    variables:
      - tenancy_ocid
      - region
      - compartment_id
      - display_name_prefix
  - title: "Autonomous Database Configuration"
    variables:
      - db_name
      - db_is_free_tier
      - db_license_model
      - db_password
      - db_version
      - db_size_in_tbs
      - db_enable_auto_scaling
      - db_compute_model
      - db_compute_count
      - db_workload
      - db_data_safe_status
      - db_operations_insights_status
      - db_database_management_status
  - title: "Workshop Settings"
    variables:
      - llm_secret
      - tag
      - run_post_load_procedures
  - title: "Hidden Variables"
    visible: false
    variables:
      - user_ocid
      - fingerprint
      - private_key_path
# General Configuration Variables
variables:
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy.
    type: string
    required: true
    visible: false
  region:
    title: Region
    description: Select Region where all resources will be created.
    type: oci:identity:region:name
    required: true
    visible: true
  compartment_id:
    title: Compartment
    description: Choose the compartment where all resources will be provisioned.
    type: oci:identity:compartment:id
    required: true
    visible: true
  display_name_prefix:
    title: Display Name Prefix
    type: string
    default: "Oracle MovieStream"
    description: Enter the Display name for the solution.
    required: true
    visible: true
# Autonomous Database Configuration Variables
  db_name:
    title: Database Name
    description: "Provide Database name. Constraints: 12 alphanumeric characters only. No Spaces."
    required: true
    type: string
    maxLength: 30
  db_is_free_tier:
    title: Do do want a always Free Oracle Autonomous Database instance?
    description: "Provision Always Free Oracle Autonomous Database instance (20 GB Storage)?"
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true
  db_license_model:
    title: "Provision Paid Oracle Autonomous Database instance (4 ECPUs 1 TB Storage) - License Included or BYOL?"
    description: "Note: This configuration can be changed later from the OCI console."
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_password:
    title: Database Admin Password
    description: "Provide admin password. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
    type: password
    required: true
    confirmation: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  db_version:
    title: "A valid Oracle Database version for Autonomous Database"
    description: "A valid Oracle Database version for Autonomous Database"
    type: enum
    enum:
      - "19c"
    default: "19c"
    required: true
    visible: true
  db_size_in_tbs:
    title: "The quantity of data in the database, in terabytes."
    description: "The quantity of data in the database, in terabytes."
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
      - 128
    default: 1
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_enable_auto_scaling:
    title: Indicates if auto scaling is enabled for the Autonomous Database CPU core count. 
    description: "Indicates if auto scaling is enabled for the Autonomous Database CPU core count. "
    type: enum
    enum:
      - true
      - false
    default: false
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_compute_model:
    title: "The compute model of the Autonomous Database ECPUs"
    description: "The compute model of the Autonomous Database ECPUs"
    type: enum
    enum:
      - "ECPU"
    default: "ECPU"
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_compute_count:
    title: The number of ECPUs cores to be made available to the database 
    description: "The number of ECPU cores to enable. For ECPUs count needs to be minimum 2 and maximum 512 ECPUs"
    type: string
    default: 4
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_workload:
    title: Autonomous Database Type of workload. 
    description: "Autonomous Database Type of workload."
    type: enum
    enum:
      - "DW"
    default: "DW"
    required: true
    visible: false
  db_data_safe_status:
    title: "Status of the Data Safe registration for this Autonomous Database"
    description: "Status of the Data Safe registration for this Autonomous Database. Could be REGISTERED or NOT_REGISTERED."
    type: enum
    enum:
      - "NOT_REGISTERED"
      - "REGISTERED"
    default: "NOT_REGISTERED"
    required: true
    visible: true 
  db_database_management_status:
    title: "Status of Database Management for this Autonomous Database"
    description: "Status of Database Management for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true 
  db_operations_insights_status:
    title: "Status of Operations Insights for this Autonomous Database"
    description: "Status of Operations Insights for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true  
# Workshop Settings
  llm_secret:
    title: Secret API key used to connect to AI model 
    description: "Enter your secret API key"
    type: string
    default: null
    required: true
    visible: true     
  tag:
    title: Pick the datasets to load. 
    description: "Pick one from below"
    type: enum
    enum:
      - "gen-ai"
    default: "gen-ai"
    required: true
    visible: true 
  run_post_load_procedures:
    title: Run procedures after loading data
    description: "Pick one from below"
    type: enum
    enum:
      - true
      - false
    default: true
    required: true
    visible: true 
outputs:
  ADW_Database_db_connection:
    type: string
    title: ADW_Database_db_connection
    visible: true
  ADW_Database_private_endpoint_ip:
    type: string
    title: ADW_Database_private_endpoint_ip
    visible: true
  Database_Actions:
    type: link
    title: url
    visible: true
  database_fully_qualified_name:
    type: string
    title: database_fully_qualified_name
    visible: true      
  graph_studio_url:
    type: link
    title: graph_studio_url
    visible: false
  machine_learning_user_management_url:
    type: link
    title: machine_learning_user_management_url
    visible: true
  apex_url:
    type: link
    title: apex_url
    visible: true    
  select_ai_demo_url:
    type: link
    title: select_ai_demo_url
    visible: true      
  adb_admin_password:
    type: string
    title: adb_admin_password
    visible: false      
  adb_user_name:
    type: string
    title: adb_user_name
    visible: true      
  adb_user_password:
    type: string
    title: adb_user_password
    visible: true        
outputGroups:
  - title: Database details
    outputs:
      - ADW_Database_db_connection
      - ADW_Database_private_endpoint_ip
      - database_fully_qualified_name
  - title: ADB user details
    outputs: 
      - Database_Actions
      - apex_url
      - graph_studio_url
      - machine_learning_user_management_url
      - adb_user_name
      - adb_user_password
primaryOutputButton: graph_studio_url

