
CREATE USER VIVEK_V_RAJ IDENTIFIED BY "${db_password}";
GRANT CREATE SESSION TO VIVEK_V_RAJ;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO VIVEK_V_RAJ;
grant create any directory to VIVEK_V_RAJ;
grant connect,resource to VIVEK_V_RAJ;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO VIVEK_V_RAJ;
GRANT UNLIMITED TABLESPACE TO VIVEK_V_RAJ ;
grant execute on dbms_lock to VIVEK_V_RAJ;
ALTER USER VIVEK_V_RAJ DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
ALTER USER VIVEK_V_RAJ QUOTA UNLIMITED ON SYSTEM;
ALTER USER VIVEK_V_RAJ QUOTA UNLIMITED ON DBFS_DATA;
ALTER USER VIVEK_V_RAJ QUOTA UNLIMITED ON DATA;


CREATE ROLE ODI_LINEAGE_USER;
GRANT CONNECT, RESOURCE TO ODI_LINEAGE_USER;
CREATE ROLE "INSIGHT$IMPL";
CREATE ROLE ADP_SERVICE$IMPL;
CREATE ROLE LINEAGE_ADMIN;
CREATE ROLE CLOUD_INGEST$IMPL;
CREATE ROLE CLOUD_INGEST_USER;
CREATE ROLE CLOUD_INGEST_ADMIN;
CREATE ROLE INSIGHT_ADMIN;
CREATE ROLE INGEST_REC_INTERNAL$IMPL;
CREATE ROLE ODI_LINEAGE_ADMIN;


CREATE USER DMISHRA IDENTIFIED BY "${db_password}" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO DMISHRA;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO DMISHRA;
grant create any directory to DMISHRA;
grant connect,resource to DMISHRA;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO DMISHRA;
GRANT UNLIMITED TABLESPACE TO DMISHRA ;
grant execute ON dbms_lock TO DMISHRA;
ALTER USER DMISHRA DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;

ALTER USER DMISHRA QUOTA UNLIMITED ON SYSTEM;
ALTER USER DMISHRA QUOTA UNLIMITED ON DBFS_DATA;
ALTER USER DMISHRA QUOTA UNLIMITED ON DATA;
ALTER USER DMISHRA quota unlimited on TBS_OML;
GRANT CREATE VIEW TO DMISHRA;
GRANT PYQADMIN TO DMISHRA;
GRANT CREATE MINING MODEL TO DMISHRA;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO DMISHRA;
GRANT CREATE MINING MODEL TO DMISHRA;
GRANT SELECT ANY MINING MODEL TO DMISHRA;
GRANT oml_developer TO DMISHRA;

GRANT EXECUTE ON DBMS_CLOUD_AI TO DMISHRA;
GRANT EXECUTE ON DBMS_CLOUD TO DMISHRA;

BEGIN
    DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(
        host => 'api.openai.com',
        ace => xs$ace_type(privilege_list => xs$name_list('http'),
        principal_name => 'DMISHRA',
        principal_type => xs_acl.ptype_db)
    );
END;
/

BEGIN
    DBMS_CLOUD.CREATE_CREDENTIAL(
        credential_name => 'DMISHRA',
        username        => 'OPENAI',
        password        => '${llmpw}'
    );
END;
/

BEGIN
    DBMS_CLOUD_AI.CREATE_PROFILE(
        profile_name => 'DMISHRA',
        attributes   => '{"provider": "openai",
                          "model": "gpt-4",
                          "credential_name": "DMISHRA",
                          "comments": "true",
                          "object_list":
                              [{"owner": "DMISHRA", "name": "ESTIMATED_COST_REVENUE"},
                               {"owner": "DMISHRA", "name": "NEAREST_NEIGHBOR"},
                               {"owner": "DMISHRA", "name": "SITE_OPERATION_COST_REVENUE"}]
                         }',
        status       => 'ENABLED',
        description  => 'AI profile to use OpenAI for SQL translation'
    );
END;
/

EXEC DBMS_CLOUD_AI.SET_PROFILE('DMISHRA');

exit;
/