CREATE OR REPLACE SYNONYM DMISHRA.SITE FOR COMMS_LAKEHOUSE_TELECOM_TOWER.SITE;
CREATE OR REPLACE SYNONYM DMISHRA.NEW_DEVELOPMENT_ROLLOUT FOR COMMS_LAKEHOUSE_TELECOM_TOWER.NEW_DEVELOPMENT_ROLLOUT;

exit;
/